
name: modify_gp_agent_config
label: 7. Modify the GobalProtect Agent configuration

description: Modify the GlobalProtect agent configuration to support authentication policy.

extends:

type: panos

labels:
  collection:
    - X509 Certificates

variables:
  - name: config_name
    description: name of the agent configuration
    default: default_agent_config
    type_hint: text
  - name: udp_port
    description: Network Port for Inbound Authentication Prompts (UDP) Change only if necessary.
    default: 4501
    type_hint: text
  - name: trusted_mfa_gateways
    description: Trusted MFA Gateway(s)
    default: 192.168.45.20
    type_hint: text

snippets:
    - name: captive_portal
      xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-portal/entry[@name='Portal-1']/client-config/configs/entry[@name='Pre-logon_User']/gp-app-config/config
      file: 0-modify-agent.xml