
name: modify_gp_agent_config_rest
label: 7b. Modify the GobalProtect Agent configuration-rest

description: Modify the GlobalProtect agent configuration to support authentication policy.

extends:

type: rest

labels:
  collection:
    - X509 Certificates

variables:
  - name: portal_name
    description: Name of the portal
    default: Portal-1
    type_hint: text
  - name: config_name
    description: name of the agent configuration
    default: default_agent_config
    type_hint: text
  - name: udp_port
    description: Network Port for Inbound Authentication Prompts (UDP) Change only if necessary.
    default: 4501
    type_hint: text
  - name: trusted_mfa_gateways
    description: Trusted MFA Gateway(s)
    default: 192.168.45.20
    type_hint: text
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
  - name: pre-logon_rule
    path: https://{{ TARGET_IP }}/api/?type=config&action=edit&key={{ api_key }}&xpath=/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-portal/entry[@name='Portal-1']/client-config/configs/entry[@name='Pr
      e-logon_User']/gp-app-config/config/entry[@name='mfa-enabled']/value&element=<value><member>yes</member></value>
    output_type: xml
    #outputs:
    #  - name: profileName
    #    capture_pattern: result/{{ profile }}
